import RightBar from "@/components/rightbar";
import { SideBar } from "@/components/sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-white`}>
        <div className="flex overy">
          <SideBar />
          {children}
        </div>
      </body>
    </html>
  );
}
